workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        BUILD_TYPE: debug    # Can be debug or release
      java: 17               # Use Java 17 for compatibility with AGP
      android_signing:
        - keystore_reference: your_keystore_reference  # Optional for signed builds
    scripts:
      - name: Install dependencies
        script: ./gradlew dependencies

      - name:
